
musicFiles = [
    "music/Kevin MacLeod - All This.ogg",
	"music/Kevin MacLeod - Amazing Plan.ogg",
	"music/Kevin MacLeod - Arcadia.ogg",
	"music/Kevin MacLeod - Aurea Carmina.ogg",
	"music/Kevin MacLeod - Barroom Ballet.ogg",
	"music/Kevin MacLeod - Basement Floor.ogg",
	"music/Kevin MacLeod - Black Vortex.ogg",
	"music/Kevin MacLeod - Breaktime.ogg",
	"music/Kevin MacLeod - Cipher.ogg",
	"music/Kevin MacLeod - Cut and Run.ogg",
	"music/Kevin MacLeod - Dance of the Sugar Plum Fairies.ogg",
	"music/Kevin MacLeod - Darkest Child.ogg",
	"music/Kevin MacLeod - Exhilarate.ogg",
	"music/Kevin MacLeod - Fluffing a Duck.ogg",
	"music/Kevin MacLeod - Frost Waltz.ogg",
	"music/Kevin MacLeod - Gold Rush.ogg",
	"music/Kevin MacLeod - Heartbreaking.ogg",
	"music/Kevin MacLeod - Hidden Agenda.ogg",
	"music/Kevin MacLeod - Hitman.ogg",
	"music/Kevin MacLeod - Hyperfun.ogg",
	"music/Kevin MacLeod - Ice Flow.ogg",
	"music/Kevin MacLeod - Investigations.ogg",
	"music/Kevin MacLeod - Jaunty Gumption.ogg",
	"music/Kevin MacLeod - Jingle Bells.ogg",
	"music/Kevin MacLeod - Killing Time.ogg",
	"music/Kevin MacLeod - Kool Kats.ogg",
	"music/Kevin MacLeod - Local Forecast - Elevator.ogg",
	"music/Kevin MacLeod - Local Forecast.ogg",
	"music/Kevin MacLeod - Look Busy.ogg",
	"music/Kevin MacLeod - Mariachi Snooze.ogg",
	"music/Kevin MacLeod - Merry Go.ogg",
	"music/Kevin MacLeod - Mister Exposition.ogg",
	"music/Kevin MacLeod - Move Forward.ogg",
	"music/Kevin MacLeod - Movement Proposition.ogg",
	"music/Kevin MacLeod - MTA.ogg",
	"music/Kevin MacLeod - Pixel Peeker Polka - faster.ogg",
	"music/Kevin MacLeod - Quirky Dog.ogg",
	"music/Kevin MacLeod - Scheming Weasel (faster Version).ogg",
	"music/Kevin MacLeod - Sneaky Adventure.ogg",
	"music/Kevin MacLeod - Sneaky.ogg",
	"music/Kevin MacLeod - Spazzmatica Polka.ogg",
	"music/Kevin MacLeod - The Builder.ogg",
	"music/Kevin MacLeod - The Descent.ogg",
	"music/Kevin MacLeod - The House of Leaves.ogg",
	"music/Kevin MacLeod - Truth of the Legend.ogg",
	"music/Kevin MacLeod - Volatile Reaction.ogg",
	"music/Kevin MacLeod - Wallpaper.ogg",
	"music/Kevin MacLeod - Who Likes to Party.ogg",
	"music/Kevin MacLeod Archive - Kevin MacLeod： Meatball Parade.ogg",
	"music/Kevin MacLeod Archive - Kevin MacLeod： Run Amok.ogg",
	"music/Kevin MacLeod Archive - Kevin MacLeod： The Cannery.ogg",
	"music/nocturnes.mp3"
]
